//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiger.Types {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tiger.Types.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to initialize Tiger.Types.Either`2[TLeft,TRight] with null value..
        /// </summary>
        public static string EitherConstructNull {
            get {
                return ResourceManager.GetString("EitherConstructNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance has not been initialized..
        /// </summary>
        public static string EitherIsBottom {
            get {
                return ResourceManager.GetString("EitherIsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is in an invalid state..
        /// </summary>
        public static string EitherIsNotLeft {
            get {
                return ResourceManager.GetString("EitherIsNotLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is in an invalid state..
        /// </summary>
        public static string EitherIsNotRight {
            get {
                return ResourceManager.GetString("EitherIsNotRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided type is not compatible with Tiger.Types.Option`1[TSome]..
        /// </summary>
        public static string IncompatibleType {
            get {
                return ResourceManager.GetString("IncompatibleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to initialize Tiger.Types.Option`1[TSome] with null value..
        /// </summary>
        public static string OptionConstructNull {
            get {
                return ResourceManager.GetString("OptionConstructNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is in an invalid state..
        /// </summary>
        public static string OptionIsNone {
            get {
                return ResourceManager.GetString("OptionIsNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This result evaluated to null..
        /// </summary>
        public static string ResultIsNull {
            get {
                return ResourceManager.GetString("ResultIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is in an invalid state..
        /// </summary>
        public static string TryIsNotErr {
            get {
                return ResourceManager.GetString("TryIsNotErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This instance is in an invalid state..
        /// </summary>
        public static string TryIsNotOk {
            get {
                return ResourceManager.GetString("TryIsNotOk", resourceCulture);
            }
        }
    }
}
